In [2]:
import numpy as np
from typing import *

In [42]:
a = [[1, 2, 3], [0, 4, 5], [1, 0, 6]]
a2 = [[1, 2, 3, 7], [.213, 4, 5, 34], [1, 2,5, -6846], [1, 496846, 6, 846]]

In [13]:
def mul(a, b: List[List]):
    return [[a * b[i][j] for j in range(len(b[i]))] for i in range(len(b))]

In [14]:
def determinant_2_2(a: List[List]):
    y = a[0][0]*a[1][1] - a[0][1]*a[1][0]
    return y

In [15]:
determinant_2_2([[1, 2], [3, 4]])

-2

In [36]:
def determinant_3_3(a: List[List]):
    ans = 0
    for i1 in range(3):
        z = a[0][i1]
        y = 0
        if i1 == 0:
            y = determinant_2_2(list(map(lambda x: x[1:], a[1:])))
        elif i1 == 1:
            y = -determinant_2_2(list(map(lambda x: x[0:3:2], a[1:])))
        elif i1 == 2:
            y = determinant_2_2(list(map(lambda x: x[:1+1], a[1:])))
        ans += y*z
    return ans

In [17]:
def transpose(a: List[List]):
    b = [[0 for _ in range(len(a))] for __ in range(len(a[0]))]
    for i in range(len(a)):
        for j in range(len(a[i])):
            b[j][i] = a[i][j]
    return b

In [18]:
transpose(a)

[[1, 0, 1], [2, 4, 0], [3, 5, 6]]

In [32]:
def determinant_any_sq(a: List[List]):
    if len(a) == 1:
        return a[0][0]
    elif len(a) == 2:
        return determinant_2_2(a)
    else:
        ans = 0
        for j1 in range(len(a)):
            to_det_i_range = list(set(range(0, len(a))) - {0})
            to_det_j_range = list(set(range(0, len(a[0]))) - {j1})
            z = a[0][j1]
            to_det = [[a[ii][jj] for jj in to_det_j_range] for ii in to_det_i_range]
            det = determinant_any_sq(to_det)
            if j1 % 2 == 1:
                det *= -1
            ans += det*z
        return ans

In [28]:
def inv_3_3(a: List[List]):
    b = [[0 for _ in range(len(a[0]))] for __ in range(len(a))]
    for i in range(len(a)):
        for j in range(len(a[i])):
            to_det_i_range = list(set(range(0, len(a))) - {i})
            to_det_j_range = list(set(range(0, len(a[i]))) - {j})
            to_det_i_range.sort();to_det_j_range.sort()
            to_det = [[a[ii][jj] for jj in to_det_j_range] for ii in to_det_i_range]
            det = determinant_2_2(to_det)
            if (i == 1) ^ (j == 1):
                det*=-1
            b[i][j] = det
    return mul(1.0/determinant_3_3(a), transpose(b))

In [21]:
i = 2
j = 1
(i == 1) ^ (j == 1)

True

In [43]:
determinant_any_sq(a2)

-14880870823.606

In [44]:
np.linalg.det(a2)

-14880870823.606

In [37]:
determinant_3_3(a)

22

In [23]:
np.linalg.det(np.array(a))

22.000000000000004

In [25]:
list(map(lambda x: x[1:], a[:1+1]))

[[0, 2], [-1, 1]]

In [33]:
list(map(lambda x: x[0:3:2], a[1:]))

[[2, 1], [1, -1]]

In [35]:
list(map(lambda x: x[:1+1], a[1:]))

[[2, -1], [1, 3]]

In [67]:
np.array(inv_3_3(a))

array([[ 1.09090909, -0.54545455, -0.09090909],
       [ 0.22727273,  0.13636364, -0.22727273],
       [-0.18181818,  0.09090909,  0.18181818]])

In [64]:
np.linalg.inv(np.array(a))

array([[ 1.09090909, -0.54545455, -0.09090909],
       [ 0.22727273,  0.13636364, -0.22727273],
       [-0.18181818,  0.09090909,  0.18181818]])

In [65]:
determinant_3_3(a)*determinant_3_3(inv_3_3(a))

0.9999999999999999

In [66]:
np.linalg.det(np.array(a))*np.linalg.det(np.linalg.inv(np.array(a)))

0.9999999999999999

In [47]:
np.linalg.det(np.array(a))

12.000000000000005

In [48]:
np.linalg.det(np.linalg.inv(np.array(a)))

0.08333333333333329

In [49]:
determinant_3_3(np.linalg.inv(np.array(a)))

0.08333333333333331

In [50]:
np.linalg.det(list(map(lambda x: x[:1+1], a[1:])))

7.000000000000001

In [51]:
determinant_2_2(list(map(lambda x: x[:1+1], a[1:])))

7

In [45]:
import math

## Rotation 

In [52]:
def get_rotation_matrix(angle: float):
    b = [[] for _ in range(2)]
    b[0] = [math.cos(angle), -math.sin(angle)]
    b[1] = [math.sin(angle), math.cos(angle)]
    return b

In [67]:
def dot(a: List[List], b: List[List]):
    c = [[0 for j in range(len(b[0]))] for i in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for i2 in range(len(a[0])):
                c[i][j] += a[i][i2]*b[i2][j]
    return c
def add(a: List[List], b: List[List]):
    return [[a[i][ii] + b[i][ii] for ii in range(len(a[i]))] for i in range(len(a))]
def diff(a: List[List], b: List[List]):
    return [[a[i][ii] - b[i][ii] for ii in range(len(a[i]))] for i in range(len(a))]


def rotate_points(points, angle, origin_point):
    points_mat = transpose([[p[0]-origin_point[0], p[1]-origin_point[1]] for p in points])
    points_out = transpose(dot(get_rotation_matrix(angle), points_mat))
    return [[p[0]+origin_point[0], p[1]+origin_point[1]] for p in points_out]

print(np.array(rotate_points([[1, 1], [1, 2], [2, 2], [2, 1]], math.pi, [0.5, 0.5])))

[[-1. -1.]
 [-1. -2.]
 [-2. -2.]
 [-2. -1.]]
